const carros2024 = [
     {
        nome: 'Ferrari',
        sigla:'FER',
        velocidadeMaxima: 340,
        potencia: 800,
        consumo: 5.5,
        aceleracao: 2.9,
        preco: 300000,
     },
    {
        nome: 'Lamborghini',
        sigla:'LAM',
        velocidadeMaxima: 355,
        potencia: 770,
        consumo: 6.2,
        aceleracao: 2.8,
        preco: 330000,
    },
    {
        nome: 'BMW',
        sigla:'BMW',
        velocidadeMaxima: 200,
        potencia: 500,
        consumo: 7.5,
        aceleracao: 4.0,
        preco: 120000,
    },
    {
        nome: 'Honda',
        sigla:'HON',
        velocidadeMaxima: 220,
        potencia: 200,
        consumo: 12.0,
        aceleracao: 6.5,
        preco: 35000,
    },
    {
        nome: 'Ford',
        sigla:'FOR',
        velocidadeMaxima: 230,
        potencia: 250,
        consumo: 11.0,
        aceleracao: 6.0,
        preco: 40000,
    },
    {
        nome: 'Audi',
        sigla:'AUD',
        velocidadeMaxima: 290,
        potencia: 650,
        consumo: 7.0,
        aceleracao: 3.6,
        preco: 11500,
    },
    {
        nome: 'Porsche',
        sigla:'POR',
        velocidadeMaxima: 180,
        potencia: 400,
        consumo: 5.8,
        aceleracao: 3.9,
        preco: 25000,
    },
    {
        nome: 'Aston Martin',
        sigla:'ASM',
        velocidadeMaxima: 500,
        potencia: 700,
        consumo: 4.8,
        aceleracao: 5.6,
        preco: 42000,
    },
    {
        nome: 'Rolls Royce',
        sigla:'ROY',
        velocidadeMaxima: 680,
        potencia: 800,
        consumo: 3.8,
        aceleracao: 6.8,
        preco: 50000,
    }
];

export default carros2024;